import tables

type OPTYPE* = enum
    NN, NN_OPTIM, NN_LOSS, NN_ACTIV, NN_BOOSTED, IO, IO_BIGQUERY, IO_EVENT, 
    IO_RPC, CONTROL, CONTROL_SDCA, INTERNAL_PY, INTERNAL, DATA, DATA_ITER, 
    STRING, PROB, IMAGE, DATASTRUCTURE, ARRAY, RAGGED, MATH, LOOKUP, QUEUE,
    BITWISE, AUDIO, GEN

const opsmap* = {
    "GcsConfigureBlockCache"                                      : IO, #If the values are the same as already configured values, this op is a no-op. If they are different, the current contents of the block cache is dropped, and a new block cache is created fresh.
    "GenerateBigQueryReaderPartitions"                            : IO_BIGQUERY, #This op should not be used directly by clients. Instead, the bigquery_reader_ops.py file defines a clean interface to the reader.
    "Fact"                                                        : INTERNAL, #
    "ResourceApplyAddSign"                                        : NN_OPTIM, #
    "ResourceSparseApplyRMSProp"                                  : NN_OPTIM, #
    "ResourceSparseApplyCenteredRMSProp"                          : NN_OPTIM, #
    "SparseApplyCenteredRMSProp"                                  : NN_OPTIM, #
    "SparseApplyRMSProp"                                          : NN_OPTIM, #
    "ApplyRMSProp"                                                : NN_OPTIM, #
    "ResourceApplyAdaMax"                                         : NN_OPTIM, #
    "ApplyAdaMax"                                                 : NN_OPTIM, #
    "ApplyAdam"                                                   : NN_OPTIM, #
    "ResourceSparseApplyKerasMomentum"                            : NN_OPTIM, #
    "ResourceApplyKerasMomentum"                                  : NN_OPTIM, #
    "ResourceSparseApplyMomentum"                                 : NN_OPTIM, #
    "ResourceApplyMomentum"                                       : NN_OPTIM, #
    "ResourceSparseApplyFtrlV2"                                   : NN_OPTIM, #
    "ResourceSparseApplyFtrl"                                     : NN_OPTIM, #
    "SparseApplyFtrl"                                             : NN_OPTIM, #
    "ApplyFtrl"                                                   : NN_OPTIM, #
    "ResourceSparseApplyAdagradDA"                                : NN_OPTIM, #
    "SparseApplyProximalAdagrad"                                  : NN_OPTIM, #
    "SparseApplyAdagradDA"                                        : NN_OPTIM, #
    "ApplyAdagradDA"                                              : NN_OPTIM, #
    "ResourceSparseApplyAdagrad"                                  : NN_OPTIM, #
    "SparseApplyAdagrad"                                          : NN_OPTIM, #
    "ResourceApplyAdagrad"                                        : NN_OPTIM, #
    "ApplyAdagrad"                                                : NN_OPTIM, #
    "SparseApplyAdadelta"                                         : NN_OPTIM, #
    "ApplyAdadelta"                                               : NN_OPTIM, #
    "ResourceSparseApplyProximalGradientDescent"                  : NN_OPTIM, #
    "ResourceApplyProximalGradientDescent"                        : NN_OPTIM, #
    "ApplyProximalGradientDescent"                                : NN_OPTIM, #
    "UnicodeDecodeWithOffsets"                                    : STRING, #
    "UnicodeTranscode"                                            : STRING, #
    "Substr"                                                      : STRING, #
    "DecodeBase64"                                                : STRING, #
    "EncodeBase64"                                                : STRING, #
    "StringSplit"                                                 : STRING, #
    "StringJoin"                                                  : STRING, #
    "ReduceJoin"                                                  : STRING, #
    "StringToHashBucketFast"                                      : STRING, #
    "StaticRegexReplace"                                          : STRING, #
    "RegexReplace"                                                : STRING, #
    "StatelessMultinomial"                                        : PROB, #
    "StatelessRandomUniformInt"                                   : PROB, #
    "StatelessRandomNormal"                                       : PROB, #
    "StatelessRandomUniform"                                      : PROB, #
    "CountUpTo"                                                   : MATH, #
    "ResourceScatterNdUpdate"                                     : ARRAY, #
    "ScatterNdUpdate"                                             : ARRAY, #
    "ScatterMax"                                                  : MATH, #
    "ScatterMul"                                                  : MATH, #
    "ScatterSub"                                                  : MATH, #
    "ScatterAdd"                                                  : MATH, #
    "ScatterUpdate"                                               : ARRAY, #
    "AssignSub"                                                   : ARRAY, #
    "Assign"                                                      : GEN, #
    "DestroyTemporaryVariable"                                    : ARRAY, #
    "TemporaryVariable"                                           : ARRAY, #
    "IsVariableInitialized"                                       : ARRAY, #
    "VariableV2"                                                  : GEN, #
    "BatchFFT2D"                                                  : MATH, #
    "BatchFFT"                                                    : MATH, #
    "IRFFT3D"                                                     : MATH, #
    "IRFFT2D"                                                     : MATH, #
    "RFFT2D"                                                      : MATH, #
    "IRFFT"                                                       : MATH, #
    "RFFT"                                                        : MATH, #
    "FFT3D"                                                       : MATH, #
    "IFFT2D"                                                      : MATH, #
    "FFT2D"                                                       : MATH, #
    "IFFT"                                                        : MATH, #
    "FFT"                                                         : MATH, #
    "WriteScalarSummary"                                          : IO_EVENT, #
    "CloseSummaryWriter"                                          : IO_EVENT, #
    "FlushSummaryWriter"                                          : IO_EVENT, #
    "CreateSummaryDbWriter"                                       : IO_EVENT, #
    "SummaryWriter"                                               : IO_EVENT, #
    "SparseFillEmptyRowsGrad"                                     : ARRAY, #
    "SparseFillEmptyRows"                                         : ARRAY, #
    "SparseSparseMinimum"                                         : ARRAY, #
    "SparseSparseMaximum"                                         : ARRAY, #
    "SparseSoftmax"                                               : NN_ACTIV, #
    "SparseDenseCwiseAdd"                                         : ARRAY, #
    "SparseDenseCwiseDiv"                                         : ARRAY, #
    "SparseReduceMax"                                             : ARRAY, #
    "SparseReshape"                                               : ARRAY, #
    "SparseReorder"                                               : ARRAY, #
    "SparseSlice"                                                 : ARRAY, #
    "SparseSliceGrad"                                             : ARRAY, #
    "SparseCross"                                                 : ARRAY, #
    "SparseConcat"                                                : ARRAY, #
    "DeserializeManySparse"                                       : ARRAY, #
    "SerializeManySparse"                                         : ARRAY, #
    "SerializeSparse"                                             : ARRAY, #
    "SparseAddGrad"                                               : ARRAY, #
    "SparseToSparseSetOperation"                                  : ARRAY, #
    "DenseToDenseSetOperation"                                    : ARRAY, #
    "_Recv"                                                       : INTERNAL, #
    "_Send"                                                       : INTERNAL, #
    "SdcaFprint"                                                  : CONTROL_SDCA, #
    "SdcaShrinkL1"                                                : CONTROL_SDCA, #
    "SdcaOptimizerV2"                                             : CONTROL_SDCA, #
    "SdcaOptimizer"                                               : CONTROL_SDCA, #
    "EagerPyFunc"                                                 : INTERNAL_PY, #
    "PyFuncStateless"                                             : INTERNAL_PY, #
    "_ScopedAllocatorSplit"                                       : INTERNAL, #but must only be used in conjunction with corresponding ScopedAllocator and ScopedAllocatorConcat instances.  In practice it is provided as inputs the backing tensor as first input, which contains the concatenated values, and a list of alias tensors as its other input and it simply outputs that second list.  This is an experimental op for internal use only.  It is possible to use this op in unsafe ways.  'concat' is the single output produced by an upstream ScopedAllocatorConcat node.  This is actually the backing tensor from a ScopedAllocator node upstream of the ScopedAllocatorConcat. 'split' is a list of tensors aliased from the backing tensor.  It will become the output of this ScopedAllocatorSplit node. 'type' is the common DataType of all of the input and output tensors. 'sa_name' is the Node name of the upstream ScopedAllocator. 'id' is the scope_id identifying the upstream ScopedAllocator. 'N' is the number of split tensors. 'shapes' is a list of the split tensor shapes.
    "_ScopedAllocator"                                            : INTERNAL, #downstream Ops as backing store for their output tensor allocations via the ScopedAllocatorMgr. Returns a reference to this value.  This is an experimental op for internal use only.  It is possible to use this op in unsafe ways.  'shapes' is a list of the shapes of the tensors that are to be allocated by this ScopedAllocator. 'shape' is the shape of the output of this Op, i.e. the 1D backing tensor from which the individual allocated tensors are aliased. 'sa_name' is the name assigned to the Node, for connectivity specification and debugging. 'id' is a non-negative integer 'scope_id' handled by the ScopedAllocatorMgr. 'expected_call_count' is the number of individual tensors expected to be allocated from the backing tensor.
    "ConsumeMutexLock"                                            : CONTROL, #
    "MutexLock"                                                   : CONTROL, #
    "MutexV2"                                                     : CONTROL, #
    "ResourceScatterUpdate"                                       : ARRAY, #
    "ResourceScatterMin"                                          : ARRAY, #
    "ResourceScatterAdd"                                          : MATH, #
    "VariableShape"                                               : ARRAY, #
    "RemoteFusedGraphExecute"                                     : CONTROL, #
    "RandomPoissonV2"                                             : PROB, #
    "RandomPoisson"                                               : PROB, #
    "RandomGammaGrad"                                             : PROB, #
    "Multinomial"                                                 : PROB, #
    "RandomShuffle"                                               : PROB, #
    "ParameterizedTruncatedNormal"                                : PROB, #
    "RandomUniformInt"                                            : PROB, #
    "RandomUniform"                                               : PROB, #
    "RaggedGather"                                                : ARRAY, #
    "BatchIFFT2D"                                                 : MATH, #
    "StringToNumber"                                              : STRING, #
    "DecodeJSONExample"                                           : INTERNAL, #
    "SerializeTensor"                                             : STRING, #
    "ParseTensor"                                                 : STRING, #
    "ParseSequenceExample"                                        : INTERNAL, #
    "ParseExample"                                                : INTERNAL, #
    "DecodeCompressed"                                            : STRING, #
    "QuantizedBatchNormWithGlobalNormalization"                   : NN, #
    "QuantizedReluX"                                              : NN_ACTIV, #
    "QuantizedRelu"                                               : NN_ACTIV, #
    "ScatterNdSub"                                                : ARRAY, #
    "QuantizedConv2D"                                             : NN, #
    "Reciprocal"                                                  : MATH, #
    "FractionalMaxPool"                                           : NN, #
    "NthElement"                                                  : ARRAY, #
    "InTopKV2"                                                    : MATH, #
    "Sub"                                                         : MATH, #
    "InTopK"                                                      : MATH, #
    "DatasetToSingleElement"                                      : DATA, #
    "SoftmaxCrossEntropyWithLogits"                               : NN_ACTIV, #
    "LogSoftmax"                                                  : NN_ACTIV, #
    "MutableHashTableV2"                                          : ARRAY, #
    "Softplus"                                                    : NN_ACTIV, #
    "Selu"                                                        : NN_ACTIV, #
    "EluGrad"                                                     : NN_ACTIV, #
    "LeakyReluGrad"                                               : NN_ACTIV, #
    "StackPush"                                                   : ARRAY, #
    "LeakyRelu"                                                   : NN_ACTIV, #
    "SparseSplit"                                                 : ARRAY, #
    "RaggedRange"                                                 : RAGGED, #
    "ReaderSerializeStateV2"                                      : STRING, #
    "Relu6"                                                       : NN_ACTIV, #
    "ReluGrad"                                                    : NN_ACTIV, #
    "All"                                                         : INTERNAL, #
    "Dilation2DBackpropInput"                                     : NN, #
    "MaxPoolGradWithArgmax"                                       : NN, #
    "MaxPoolGradGradV2"                                           : NN, #
    "MaxPoolGradV2"                                               : NN, #
    "Roll"                                                        : GEN, #
    "MaxPoolGrad"                                                 : NN, #
    "LRNGrad"                                                     : NN, #
    "MaxPool3DGradGrad"                                           : NN, #
    "Conv3DBackpropFilter"                                        : NN, #
    "Conv3D"                                                      : NN, #
    "CropAndResize"                                               : IMAGE, #
    "DepthwiseConv2dNativeBackpropFilter"                         : NN, #
    "Expm1"                                                       : MATH, #
    "Conv2DBackpropInput"                                         : NN, #
    "_NcclReduceRecv"                                             : INTERNAL, #Reduces 'input' from this op and the NcclReduceSend ops registered in the same `shared_name`. The graph should be constructed so that 'num_devices-1' devices run `_NcclReduceSend` and one device runs _NcclReduceRecv op with shared_name value `c`. Failure to do so will cause the graph execution to fail to complete.
    "Conv2D"                                                      : NN, #
    "Sin"                                                         : MATH, #
    "FusedBatchNormV2"                                            : NN, #
    "SparseMatMul"                                                : MATH, #
    "FusedBatchNorm"                                              : NN, #
    "ReduceDataset"                                               : DATA, #
    "FakeQuantWithMinMaxArgs"                                     : ARRAY, #
    "BatchNormWithGlobalNormalization"                            : NN, #
    "ApplyFtrlV2"                                                 : NN_OPTIM, #
    "Where"                                                       : GEN, #
    "_NcclReduceSend"                                             : INTERNAL, #Reduces `input` to the NcclReduceRecv op registered in the same `shared_name`. The graph should be constructed so that 'num_devices-1' devices run `_NcclReduceSend` and one device runs _NcclReduceRecv op with shared_name value `c`. Failure to do so will cause the graph execution to fail to complete.
    "GetSessionTensor"                                            : ARRAY, #
    "Min"                                                         : MATH, #
    "NcclAllReduce"                                               : INTERNAL, #
    "ReadVariableOp"                                              : INTERNAL, #
    "Lgamma"                                                      : MATH, #
    "RequantizationRange"                                         : MATH, #
    "CompareAndBitpack"                                           : ARRAY, #
    "QuantizeDownAndShrinkRange"                                  : ARRAY, #
    "QuantizedMatMul"                                             : MATH, #
    "BatchNormWithGlobalNormalizationGrad"                        : NN, #
    "Bincount"                                                    : ARRAY, #
    "DestroyResourceOp"                                           : ARRAY, #
    "HistogramFixedWidth"                                         : GEN, #
    "BatchSelfAdjointEigV2"                                       : ARRAY, #
    "NcclBroadcast"                                               : INTERNAL, #
    "Cross"                                                       : MATH, #
    "Conj"                                                        : MATH, #
    "ExperimentalSleepDataset"                                    : DATA, #
    "_MklAdd"                                                     : INTERNAL, #*NOTE*: `Add` supports broadcasting. `AddN` does not. More about broadcasting [here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
    "Real"                                                        : MATH, #
    "Dequantize"                                                  : MATH, #
    "Complex"                                                     : MATH, #
    "SparseSoftmaxCrossEntropyWithLogits"                         : NN, #
    "Cholesky"                                                    : MATH, #
    "SparseSegmentSqrtNWithNumSegments"                           : MATH, #
    "SparseSegmentMean"                                           : MATH, #
    "SparseSegmentSumWithNumSegments"                             : MATH, #
    "UnsortedSegmentProd"                                         : MATH, #
    "UnsortedSegmentSum"                                          : MATH, #
    "_ReadVariablesOp"                                            : INTERNAL, #
    "L2Loss"                                                      : NN_LOSS, #
    "Cast"                                                        : ARRAY, #
    "SegmentMax"                                                  : MATH, #
    "Atan2"                                                       : MATH, #
    "SegmentProd"                                                 : MATH, #
    "ArgMin"                                                      : MATH, #
    "ResizeBilinearGrad"                                          : IMAGE, #
    "Max"                                                         : MATH, #
    "AccumulatorApplyGradient"                                    : NN_OPTIM, #
    "SampleDistortedBoundingBoxV2"                                : IMAGE, #
    "Prod"                                                        : MATH, #
    "Sum"                                                         : MATH, #
    "SeluGrad"                                                    : NN, #
    "Select"                                                      : ARRAY, #
    "CollectiveBcastSend"                                         : ARRAY, #
    "LogicalAnd"                                                  : MATH, #
    "WriteGraphSummary"                                           : IO_EVENT, #
    "ApproximateEqual"                                            : MATH, #
    "Equal"                                                       : MATH, #
    "QuantizeV2"                                                  : MATH, #
    "GreaterEqual"                                                : MATH, #
    "ResourceScatterMax"                                          : ARRAY, #
    "Betainc"                                                     : MATH, #
    "Polygamma"                                                   : MATH, #
    "Assert"                                                      : CONTROL, #
    "Transpose"                                                   : GEN, #
    "IgammaGradA"                                                 : MATH, #
    "StringSplitV2"                                               : STRING, #
    "ImportEvent"                                                 : IO_EVENT, #
    "Igamma"                                                      : MATH, #
    "Igammac"                                                     : MATH, #
    "Mod"                                                         : MATH, #
    "Maximum"                                                     : MATH, #
    "Xlogy"                                                       : MATH, #
    "SquaredDifference"                                           : MATH, #
    "ResourceCountUpTo"                                           : MATH, #
    "RealDiv"                                                     : GEN, #
    "TruncateDiv"                                                 : GEN, #
    "StringToHashBucketStrong"                                    : STRING, #
    "QueueEnqueue"                                                : QUEUE, #
    "_MklSub"                                                     : INTERNAL, #*NOTE*: `Sub` supports broadcasting. More about broadcasting [here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
    "AsString"                                                    : STRING, #
    "Conv3DBackpropFilterV2"                                      : NN, #
    "AddV2"                                                       : MATH, #
    "TryRpc"                                                      : IO_RPC, #
    "ResourceGather"                                              : ARRAY, #
    "UniformCandidateSampler"                                     : PROB, #
    "Add"                                                         : MATH, #
    "Floor"                                                       : MATH, #
    "Ceil"                                                        : MATH, #
    "IsFinite"                                                    : MATH, #
    "MaxPool3D"                                                   : NN, #
    "IsInf"                                                       : MATH, #
    "Cumsum"                                                      : MATH, #
    "BesselI1e"                                                   : MATH, #
    "BesselI0e"                                                   : MATH, #
    "BiasAddGrad"                                                 : NN, #
    "WriteHistogramSummary"                                       : IO_EVENT, #
    "Tan"                                                         : MATH, #
    "TopKV2"                                                      : MATH, #
    "PadV2"                                                       : MATH, #
    "Cos"                                                         : MATH, #
    "Erfc"                                                        : MATH, #
    "Digamma"                                                     : MATH, #
    "BoostedTreesSerializeEnsemble"                               : NN_BOOSTED, #
    "Acosh"                                                       : MATH, #
    "Cosh"                                                        : MATH, #
    "ResourceApplyProximalAdagrad"                                : NN_OPTIM, #
    "ResourceScatterDiv"                                          : MATH, #
    "Asin"                                                        : MATH, #
    "_HostRecv"                                                   : INTERNAL, #_HostRecv requires its input on host memory whereas _Recv requires its input on device memory.
    "ExperimentalScanDataset"                                     : DATA, #
    "Log1p"                                                       : MATH, #
    "TensorArraySize"                                             : DATASTRUCTURE, #
    "Requantize"                                                  : MATH, #
    "Exp"                                                         : MATH, #
    "ScatterNdAdd"                                                : MATH, #
    "MutableHashTableOfTensors"                                   : DATASTRUCTURE, #
    "Dilation2D"                                                  : NN, #
    "DeserializeIterator"                                         : DATA_ITER, #
    "RsqrtGrad"                                                   : MATH, #
    "QuantizedInstanceNorm"                                       : MATH, #
    "Rsqrt"                                                       : MATH, #
    "InitializeTableFromTextFile"                                 : DATASTRUCTURE, #
    "SqrtGrad"                                                    : MATH, #
    "SparseSegmentSqrtN"                                          : MATH, #
    "_MklMaximum"                                                 : INTERNAL, #*NOTE*: `Maximum` supports broadcasting. More about broadcasting [here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
    "Sqrt"                                                        : MATH, #
    "InvGrad"                                                     : MATH, #
    "Inv"                                                         : MATH, #
    "ExperimentalStatsAggregatorSummary"                          : IO_EVENT, #
    "_HostCast"                                                   : INTERNAL, #_HostCast requires its input and produces its output in host memory.
    "BatchMatMul"                                                 : MATH, #
    "AccumulateNV2"                                               : ARRAY, #
    "InitializeTableFromTextFileV2"                               : DATASTRUCTURE, #
    "InitializeTable"                                             : DATASTRUCTURE, #
    "FractionalAvgPoolGrad"                                       : NN, #
    "MutableDenseHashTableV2"                                     : DATASTRUCTURE, #
    "MutableHashTable"                                            : DATASTRUCTURE, #
    "BoostedTreesCenterBias"                                      : NN_BOOSTED, #
    "HashTableV2"                                                 : DATASTRUCTURE, #
    "HashTable"                                                   : DATASTRUCTURE, #
    "LookupTableImportV2"                                         : LOOKUP, #
    "RegexFullMatch"                                              : STRING, #
    "LookupTableImport"                                           : LOOKUP, #
    "NonMaxSuppressionWithOverlaps"                               : ARRAY, #
    "LookupTableExportV2"                                         : LOOKUP, #
    "AssignVariableOp"                                            : ARRAY, #
    "LookupTableSize"                                             : LOOKUP, #
    "PaddingFIFOQueueV2"                                          : QUEUE, #
    "LookupTableFind"                                             : LOOKUP, #
    "LessEqual"                                                   : MATH, #
    "Timestamp"                                                   : GEN, #
    "MergeSummary"                                                : IO_EVENT, #
    "AvgPool"                                                     : NN, #
    "AudioSummaryV2"                                              : IO_EVENT, #
    "HistogramSummary"                                            : IO_EVENT, #
    "TensorListScatter"                                           : ARRAY, #
    "TensorListSetItem"                                           : ARRAY, #
    "ClipByValue"                                                 : GEN, #
    "TensorListReserve"                                           : ARRAY, #
    "ExperimentalThreadPoolHandle"                                : ARRAY, #
    "TensorListFromTensor"                                        : ARRAY, #
    "TensorListStack"                                             : ARRAY, #
    "_MklMul"                                                     : INTERNAL, #*NOTE*: `Mul` supports broadcasting. More about broadcasting [here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
    "TensorScatterUpdate"                                         : ARRAY, #
    "TakeDataset"                                                 : DATA, #
    "TensorListPopBack"                                           : ARRAY, #
    "TensorListLength"                                            : ARRAY, #
    "ExperimentalIndexedDatasetGet"                               : DATA, #
    "TensorListPushBackBatch"                                     : ARRAY, #
    "EmptyTensorList"                                             : ARRAY, #
    "RandomStandardNormal"                                        : PROB, #
    "Erf"                                                         : MATH, #
    "Mean"                                                        : MATH, #
    "BatchMatrixTriangularSolve"                                  : MATH, #
    "BatchMatrixSolve"                                            : MATH, #
    "QuantizedBiasAdd"                                            : NN, #
    "DataFormatVecPermute"                                        : DATASTRUCTURE, #
    "BatchCholeskyGrad"                                           : MATH, #
    "BatchMatrixInverse"                                          : MATH, #
    "DebugNumericSummary"                                         : INTERNAL, #Provide a basic summary of numeric value types, range and distribution.
    "BatchSelfAdjointEig"                                         : MATH, #
    "LookupTableFindV2"                                           : LOOKUP, #
    "Asinh"                                                       : MATH, #
    "CollectiveBcastRecv"                                         : CONTROL, #
    "TensorArrayScatterV3"                                        : DATASTRUCTURE, #
    "MatrixSquareRoot"                                            : MATH, #
    "MatrixTriangularSolve"                                       : MATH, #
    "SelfAdjointEig"                                              : MATH, #
    "Reshape"                                                     : GEN, #
    "ArgMax"                                                      : MATH, #
    "CholeskyGrad"                                                : MATH, #
    "StaticRegexFullMatch"                                        : STRING, #
    "ParseSingleSequenceExample"                                  : INTERNAL, #
    "LookupTableExport"                                           : LOOKUP, #
    "QueueDequeue"                                                : QUEUE, #
    "TensorListSplit"                                             : ARRAY, #
    "BatchMatrixSolveLs"                                          : MATH, #
    "MatrixDeterminant"                                           : MATH, #
    "FloorMod"                                                    : MATH, #
    "MatchingFiles"                                               : IO, #
    "WriteImageSummary"                                           : IO_EVENT, #
    "MatrixSolve"                                                 : MATH, #
    "TensorArrayConcatV2"                                         : DATASTRUCTURE, #
    "WriteFile"                                                   : IO, #
    "TruncatedNormal"                                             : PROB, #
    "ReadFile"                                                    : IO, #
    "FakeQuantWithMinMaxVarsPerChannelGradient"                   : ARRAY, #
    "PrintV2"                                                     : ARRAY, #
    "ReaderResetV2"                                               : IO, #
    "ReaderSerializeState"                                        : IO, #
    "ReaderNumWorkUnitsCompletedV2"                               : IO, #
    "LowerBound"                                                  : MATH, #
    "Greater"                                                     : MATH, #
    "ReaderNumWorkUnitsCompleted"                                 : IO, #
    "DecodeRaw"                                                   : IMAGE, #
    "ReaderNumRecordsProducedV2"                                  : IO, #
    "Cumprod"                                                     : MATH, #
    "ReaderReadV2"                                                : IO, #
    "Square"                                                      : MATH, #
    "IdentityReader"                                              : IO, #
    "Slice"                                                       : GEN, #
    "LMDBReader"                                                  : IO, #
    "TFRecordReaderV2"                                            : IO, #
    "TFRecordReader"                                              : IO, #
    "FixedLengthRecordReaderV2"                                   : IO, #
    "IdentityReaderV2"                                            : IO, #
    "TextLineReaderV2"                                            : IO, #
    "ShardedFilename"                                             : IO, #
    "RestoreSlice"                                                : IO, #
    "Restore"                                                     : IO, #
    "SaveSlices"                                                  : IO, #
    "Save"                                                        : IO, #
    "MergeV2Checkpoints"                                          : IO, #
    "NonMaxSuppressionV2"                                         : IMAGE, #
    "RefExit"                                                     : CONTROL, #
    "NotEqual"                                                    : MATH, #
    "LookupTableRemoveV2"                                         : LOOKUP, #
    "NonMaxSuppression"                                           : IMAGE, #
    "Tanh"                                                        : MATH, #
    "CropAndResizeGradImage"                                      : IMAGE, #
    "AdjustSaturation"                                            : IMAGE, #
    "ApplyPowerSign"                                              : NN_OPTIM, #
    "QuantizedAvgPool"                                            : NN, #
    "AdjustContrastv2"                                            : IMAGE, #
    "Rank"                                                        : GEN, #
    "EncodeJpeg"                                                  : IMAGE, #
    "TensorArrayConcat"                                           : DATASTRUCTURE, #
    "DecodeAndCropJpeg"                                           : IMAGE, #
    "DecodeJpeg"                                                  : IMAGE, #
    "RandomCrop"                                                  : IMAGE, #
    "BigQueryReader"                                              : IO_BIGQUERY, #
    "ResizeNearestNeighborGrad"                                   : IMAGE, #
    "LRN"                                                         : NN, #
    "Conv3DBackpropInputV2"                                       : NN, #
    "ResizeBilinear"                                              : IMAGE, #
    "AssignAddVariableOp"                                         : ARRAY, #
    "DepthwiseConv2dNativeBackpropInput"                          : NN, #
    "IsNan"                                                       : MATH, #
    "TensorListPushBack"                                          : ARRAY, #
    "SparseApplyMomentum"                                         : NN_OPTIM, #
    "UniqueWithCounts"                                            : GEN, #
    "ResizeBicubicGrad"                                           : IMAGE, #
    "HSVToRGB"                                                    : IMAGE, #
    "SparseSegmentMeanWithNumSegments"                            : MATH, #
    "ResizeBicubic"                                               : IMAGE, #
    "ReaderRestoreState"                                          : IO, #
    "ResizeArea"                                                  : IMAGE, #
    "ScatterMin"                                                  : MATH, #
    "FakeParam"                                                   : CONTROL, #
    "Pow"                                                         : MATH, #
    "PartitionedCall"                                             : CONTROL, #
    "Sign"                                                        : MATH, #
    "While"                                                       : GEN, #
    "Log"                                                         : MATH, #
    "_While"                                                      : INTERNAL, #
    "AddManySparseToTensorsMap"                                   : DATASTRUCTURE, #
    "FlatMapDataset"                                              : DATA, #
    "StatelessIf"                                                 : CONTROL, #
    "Angle"                                                       : MATH, #
    "RemoteCall"                                                  : CONTROL, #
    "ExperimentalMapAndBatchDataset"                              : DATA, #
    "SymbolicGradient"                                            : MATH, #
    "_ArrayToList"                                                : INTERNAL, #
    "_ListToArray"                                                : INTERNAL, #
    "_Arg"                                                        : INTERNAL, #
    "ReaderRead"                                                  : IO, #
    "MirrorPad"                                                   : ARRAY, #
    "TensorArrayV3"                                               : DATASTRUCTURE, #
    "MatrixSolveLs"                                               : MATH, #
    "ExperimentalIdentityIndexedDataset"                          : DATA, #
    "Sinh"                                                        : MATH, #
    "ExperimentalAssertNextDataset"                               : DATA, #
    "SparseReduceSumSparse"                                       : MATH, #
    "Relu"                                                        : NN_ACTIV, #
    "MatMul"                                                      : MATH, #
    "ExperimentalThreadPoolDataset"                               : DATA, #
    "SoftplusGrad"                                                : NN_ACTIV, #
    "ExperimentalIndexedDatasetMaterialize"                       : DATA, #
    "QuantizeAndDequantizeV3"                                     : ARRAY, #
    "Mul"                                                         : MATH, #
    "BatchToSpace"                                                : GEN, #
    "ExperimentalPrivateThreadPoolDataset"                        : DATA, #
    "AddSparseToTensorsMap"                                       : DATASTRUCTURE, #
    "Elu"                                                         : NN_ACTIV, #
    "ExperimentalBytesProducedStatsDataset"                       : DATA, #
    "ExperimentalIteratorGetDevice"                               : DATA_ITER, #
    "StringFormat"                                                : STRING, #
    "ExperimentalUniqueDataset"                                   : DATA, #
    "ExperimentalUnbatchDataset"                                  : DATA, #
    "TensorArrayPack"                                             : DATASTRUCTURE, #
    "ExperimentalStatsAggregatorHandle"                           : IO_EVENT, #
    "LookupTableSizeV2"                                           : LOOKUP, #
    "ExperimentalSqlDataset"                                      : DATA, #
    "TensorArrayUnpack"                                           : DATASTRUCTURE, #
    "ExperimentalSetStatsAggregatorDataset"                       : DATA, #
    "IFFT3D"                                                      : MATH, #
    "_UnaryOpsComposition"                                        : INTERNAL, #expected to create these operators.
    "BatchMatrixDeterminant"                                      : MATH, #
    "ExperimentalIgnoreErrorsDataset"                             : DATA, #
    "ExperimentalRandomDataset"                                   : DATA, #
    "PriorityQueue"                                               : QUEUE, #
    "For"                                                         : CONTROL, #
    "ExperimentalParallelInterleaveDataset"                       : DATA, #
    "Skipgram"                                                    : ARRAY, #
    "ExperimentalMatchingFilesDataset"                            : DATA, #
    "StageClear"                                                  : CONTROL, #
    "ExperimentalMapDataset"                                      : DATA, #
    "BiasAdd"                                                     : NN, #
    "ExperimentalGroupByReducerDataset"                           : DATA, #
    "CropAndResizeGradBoxes"                                      : DATASTRUCTURE, #
    "FIFOQueueV2"                                                 : QUEUE, #
    "BatchToSpaceND"                                              : ARRAY, #
    "AccumulatorSetGlobalStep"                                    : ARRAY, #
    "ExperimentalDatasetCardinality"                              : DATA, #
    "_DeviceRetval"                                               : INTERNAL, #
    "LogUniformCandidateSampler"                                  : PROB, #
    "MapDefun"                                                    : DATA, #
    "ExperimentalCSVDataset"                                      : DATA, #
    "UnsortedSegmentMin"                                          : MATH, #
    "SegmentMin"                                                  : MATH, #
    "TensorForestTreePredict"                                     : NN_BOOSTED, #
    "EncodeProto"                                                 : ARRAY, #
    "ExperimentalDirectedInterleaveDataset"                       : DATA, #
    "Minimum"                                                     : MATH, #
    "UnicodeDecode"                                               : IO, #
    "WriteSummary"                                                : IO_EVENT, #
    "Batch"                                                       : ARRAY, #
    "ParallelInterleaveDatasetV2"                                 : DATA, #
    "QueueIsClosed"                                               : QUEUE, #
    "MultiDeviceIteratorFromStringHandle"                         : DATA_ITER, #
    "MaxPoolGradGrad"                                             : NN, #
    "UnwrapDatasetVariant"                                        : DATA, #
    "WrapDatasetVariant"                                          : DATA, #
    "Stage"                                                       : ARRAY, #
    "IdentityN"                                                   : GEN, #
    "OptionalHasValue"                                            : ARRAY, #
    "Qr"                                                          : MATH, #
    "StatefulPartitionedCall"                                     : CONTROL, #
    "OptionalFromValue"                                           : ARRAY, #
    "DatasetToGraph"                                              : DATA, #
    "ExtractGlimpse"                                              : IMAGE, #
    "ExperimentalDatasetToTFRecord"                               : DATA, #
    "ShardedFilespec"                                             : IO, #
    "ResourceApplyCenteredRMSProp"                                : NN_OPTIM, #
    "SerializeIterator"                                           : DATA_ITER, #
    "SparseSegmentSqrtNGrad"                                      : MATH, #
    "VarIsInitializedOp"                                          : ARRAY, #
    "FakeQuantWithMinMaxVarsPerChannel"                           : ARRAY, #
    "WriteAudioSummary"                                           : IO_EVENT, #
    "IteratorFromStringHandle"                                    : DATA_ITER, #
    "CheckNumerics"                                               : MATH, #
    "BroadcastTo"                                                 : GEN, #
    "IteratorToStringHandle"                                      : DATA_ITER, #
    "Atanh"                                                       : MATH, #
    "MakeIterator"                                                : DATA_ITER, #
    "UniqueWithCountsV2"                                          : ARRAY, #
    "AnonymousIterator"                                           : DATA_ITER, #
    "DebugGradientRefIdentity"                                    : INTERNAL, #
    "IteratorV2"                                                  : DATA_ITER, #
    "ImmutableConst"                                              : ARRAY, #
    "BoostedTreesQuantileStreamResourceAddSummaries"              : NN_BOOSTED, #
    "Iterator"                                                    : DATA_ITER, #
    "Rpc"                                                         : IO_RPC, #
    "TFRecordDataset"                                             : DATA, #
    "SparseReduceMaxSparse"                                       : MATH, #
    "CacheDataset"                                                : DATA, #
    "MaxPoolV2"                                                   : NN, #
    "QuantizedMul"                                                : MATH, #
    "ShuffleAndRepeatDataset"                                     : DATA, #
    "_NcclBroadcastSend"                                          : INTERNAL, #Sends `input` to the _NcclBroadcastRecv ops registered in the same `shared_name`. The graph should be constructed so that one device runs `_NcclBroadcastSend` and `num_devices-1` devices run _NcclBroadcastRecv ops with shared_name value `c`. Failure to do so will cause the graph execution to fail to complete.
    "CudnnRNN"                                                    : NN, #
    "BatchDataset"                                                : DATA, #
    "SoftsignGrad"                                                : NN_ACTIV, #
    "SetSize"                                                     : ARRAY, #
    "WindowDataset"                                               : DATA, #
    "ResourceApplyRMSProp"                                        : NN_OPTIM, #
    "MaxPool3DGrad"                                               : NN, #
    "InterleaveDataset"                                           : DATA, #
    "TanhGrad"                                                    : MATH, #
    "BoostedTreesTrainingPredict"                                 : NN_BOOSTED, #
    "LoopCond"                                                    : CONTROL, #
    "ParallelMapDataset"                                          : DATA, #
    "ReciprocalGrad"                                              : MATH, #
    "QuantizedReshape"                                            : ARRAY, #
    "MapDataset"                                                  : DATA, #
    "SkipDataset"                                                 : DATA, #
    "Conv2DBackpropFilter"                                        : NN, #
    "IteratorGetNextSync"                                         : DATA_ITER, #
    "ReaderNumRecordsProduced"                                    : IO, #
    "ModelDataset"                                                : DATA, #
    "ReaderReadUpToV2"                                            : IO, #
    "QueueDequeueV2"                                              : QUEUE, #
    "ReaderReadUpTo"                                              : IO, #
    "Unpack"                                                      : ARRAY, #
    "ConcatenateDataset"                                          : DATA, #
    "PlaceholderV2"                                               : ARRAY, #
    "GeneratorDataset"                                            : DATA, #
    "TensorSliceDataset"                                          : DATA, #
    "StringToHashBucket"                                          : STRING, #
    "Softsign"                                                    : MATH, #
    "QuantizedAdd"                                                : MATH, #
    "RandomShuffleQueueV2"                                        : QUEUE, #
    "SparseTensorSliceDataset"                                    : DATA, #
    "TensorDataset"                                               : DATA, #
    "TensorListElementShape"                                      : ARRAY, #
    "NcclReduce"                                                  : ARRAY, #
    "ApplyProximalAdagrad"                                        : NN_OPTIM, #
    "Svd"                                                         : MATH, #
    "SparseSegmentMeanGrad"                                       : MATH, #
    "MatrixExponential"                                           : MATH, #
    "GatherNd"                                                    : GEN, #
    "QueueCloseV2"                                                : QUEUE, #
    "MaxPool"                                                     : NN, #
    "OrderedMapClear"                                             : DATASTRUCTURE, #
    "OrderedMapSize"                                              : DATASTRUCTURE, #
    "TensorArrayCloseV3"                                          : DATASTRUCTURE, #
    "SaveV2"                                                      : IO, #
    "OrderedMapStage"                                             : DATASTRUCTURE, #
    "RandomGamma"                                                 : PROB, #
    "QuantizedResizeBilinear"                                     : IMAGE, #
    "OrderedMapIncompleteSize"                                    : DATASTRUCTURE, #
    "MapIncompleteSize"                                           : DATASTRUCTURE, #
    "MatrixInverse"                                               : MATH, #
    "ApplyMomentum"                                               : NN_OPTIM, #
    "Acos"                                                        : MATH, #
    "ExperimentalGroupByWindowDataset"                            : DATA, #
    "ResourceApplyAdamWithAmsgrad"                                : NN_OPTIM, #
    "_NcclBroadcastRecv"                                          : INTERNAL, #Sends data of shape `shape` from the _NcclBroadcastSend op registered in the same `shared_name`. The graph should be constructed so that one device runs `_NcclBroadcastSend` and `num_devices-1` devices run _NcclBroadcastRecv ops with shared_name value `c`. Failure to do so will cause the graph execution to fail to complete.
    "SegmentSum"                                                  : MATH, #
    "TextLineDataset"                                             : DATA, #
    "TensorSummaryV2"                                             : IO_EVENT, #
    "Unbatch"                                                     : ARRAY, #
    "MapUnstage"                                                  : DATASTRUCTURE, #
    "TopK"                                                        : MATH, #
    "ConjugateTranspose"                                          : MATH, #
    "MapPeek"                                                     : DATASTRUCTURE, #
    "SparseTensorDenseMatMul"                                     : MATH, #
    "FusedBatchNormGradV2"                                        : ARRAY, #
    "BarrierReadySize"                                            : ARRAY, #
    "MapStage"                                                    : DATASTRUCTURE, #
    "Unstage"                                                     : ARRAY, #
    "Variable"                                                    : GEN, #
    "TensorArray"                                                 : DATASTRUCTURE, #
    "SigmoidGrad"                                                 : NN_ACTIV, #
    "TensorListGather"                                            : ARRAY, #
    "DeleteSessionTensor"                                         : ARRAY, #
    "ResourceApplyAdam"                                           : NN_OPTIM, #
    "ResourceSparseApplyAdadelta"                                 : NN_OPTIM, #
    "Sigmoid"                                                     : NN_ACTIV, #
    "ResourceApplyAdagradDA"                                      : NN_OPTIM, #
    "SparseToDense"                                               : ARRAY, #
    "Bitcast"                                                     : GEN, #
    "GetSessionHandleV2"                                          : ARRAY, #
    "FakeQuantWithMinMaxVars"                                     : ARRAY, #
    "BarrierIncompleteSize"                                       : ARRAY, #
    "Any"                                                         : ARRAY, #
    "TensorForestCreateTreeVariable"                              : NN_BOOSTED, #
    "BatchFunction"                                               : DATA, #
    "BatchDatasetV2"                                              : DATA, #
    "SelfAdjointEigV2"                                            : ARRAY, #
    "Pack"                                                        : ARRAY, #
    "BarrierClose"                                                : ARRAY, #
    "PyFunc"                                                      : INTERNAL_PY, #
    "AddN"                                                        : MATH, #
    "TensorArrayV2"                                               : DATASTRUCTURE, #
    "ResourceApplyGradientDescent"                                : NN_OPTIM, #
    "MatrixLogarithm"                                             : MATH, #
    "BarrierTakeMany"                                             : ARRAY, #
    "ResourceSparseApplyProximalAdagrad"                          : NN_OPTIM, #
    "Neg"                                                         : MATH, #
    "Barrier"                                                     : ARRAY, #
    "Div"                                                         : MATH, #
    "TensorArraySizeV2"                                           : DATASTRUCTURE, #
    "AdjustContrast"                                              : IMAGE, #
    "MultiDeviceIteratorInit"                                     : DATA_ITER, #
    "ComplexAbs"                                                  : MATH, #
    "RGBToHSV"                                                    : IMAGE, #
    "ListDiff"                                                    : ARRAY, #
    "TensorArrayScatterV2"                                        : DATASTRUCTURE, #
    "RFFT3D"                                                      : MATH, #
    "TensorArrayGatherV2"                                         : DATASTRUCTURE, #
    "ReaderRestoreStateV2"                                        : CONTROL, #
    "_DeviceArg"                                                  : INTERNAL, #
    "StagePeek"                                                   : ARRAY, #
    "TensorArrayReadV2"                                           : DATASTRUCTURE, #
    "AudioSpectrogram"                                            : IO_EVENT, #
    "TensorArrayRead"                                             : DATASTRUCTURE, #
    "SparseAdd"                                                   : MATH, #
    "BitwiseXor"                                                  : BITWISE, #
    "DenseToSparseSetOperation"                                   : ARRAY, #
    "TensorArrayWriteV2"                                          : DATASTRUCTURE, #
    "TensorArrayWrite"                                            : DATASTRUCTURE, #
    "ReverseSequence"                                             : ARRAY, #
    "TensorArrayGatherV3"                                         : DATASTRUCTURE, #
    "FilterByLastComponentDataset"                                : DATA, #
    "ShuffleDataset"                                              : DATA, #
    "DivNoNan"                                                    : MATH, #
    "EditDistance"                                                : GEN, #
    "AvgPoolGrad"                                                 : NN, #
    "ParallelConcat"                                              : ARRAY, #
    "RangeDataset"                                                : DATA, #
    "UnsortedSegmentMax"                                          : MATH, #
    "TensorArrayGradWithShape"                                    : DATASTRUCTURE, #
    "MultiDeviceIteratorToStringHandle"                           : DATA_ITER, #
    "TensorArrayGradV3"                                           : DATASTRUCTURE, #
    "SparseApplyFtrlV2"                                           : NN_OPTIM, #
    "StackPop"                                                    : DATASTRUCTURE, #
    "Stack"                                                       : GEN, #
    "Abs"                                                         : MATH, #
    "Gather"                                                      : GEN, #
    "TensorArrayReadV3"                                           : DATASTRUCTURE, #
    "AvgPool3DGrad"                                               : NN, #
    "TensorArrayCloseV2"                                          : DATASTRUCTURE, #
    "ThreadUnsafeUnigramCandidateSampler"                         : PROB, #
    "StackCloseV2"                                                : DATASTRUCTURE, #
    "StackPopV2"                                                  : DATASTRUCTURE, #
    "StackPushV2"                                                 : DATASTRUCTURE, #
    "TileGrad"                                                    : ARRAY, #
    "QueueDequeueUpTo"                                            : QUEUE, #
    "AudioSummary"                                                : IO_EVENT, #
    "PaddedBatchDataset"                                          : ARRAY, #
    "StackV2"                                                     : ARRAY, #
    "SparseConditionalAccumulator"                                : ARRAY, #
    "OrderedMapUnstage"                                           : DATASTRUCTURE, #
    "_VarHandlesOp"                                               : INTERNAL, #
    "TensorArraySplitV2"                                          : DATASTRUCTURE, #
    "AccumulatorTakeGradient"                                     : ARRAY, #
    "ExtractJpegShape"                                            : IMAGE, #
    "ConditionalAccumulator"                                      : ARRAY, #
    "AccumulatorNumAccumulated"                                   : ARRAY, #
    "LogicalNot"                                                  : MATH, #
    "Lu"                                                          : MATH, #
    "QueueSize"                                                   : QUEUE, #
    "TensorArraySplitV3"                                          : DATASTRUCTURE, #
    "IteratorGetNextAsOptional"                                   : DATA_ITER, #
    "GcsConfigureCredentials"                                     : IO, #The json input can be of the format:  1. Refresh Token: {   "client_id": "<redacted>",   "client_secret": "<redacted>",   "refresh_token: "<redacted>",   "type": "authorized_user", }  2. Service Account: {   "type": "service_account",   "project_id": "<redacted>",   "private_key_id": "<redacted>",   "private_key": "------BEGIN PRIVATE KEY-----\n<REDACTED>\n-----END PRIVATE KEY------\n",   "client_email": "<REDACTED>@<REDACTED>.iam.gserviceaccount.com",   "client_id": "<REDACTED>",   # Some additional fields elided }  Note the credentials established through this method are shared across all sessions run on this runtime.  Note be sure to feed the inputs to this op to ensure the credentials are not stored in a constant op within the graph that might accidentally be checkpointed or in other ways be persisted or exfiltrated.
    "QueueDequeueManyV2"                                          : QUEUE, #
    "VarHandleOp"                                                 : ARRAY, #
    "ComputeAccidentalHits"                                       : ARRAY, #
    "QueueDequeueMany"                                            : QUEUE, #
    "ExperimentalMaxIntraOpParallelismDataset"                    : DATA, #
    "QueueEnqueueMany"                                            : QUEUE, #
    "PaddingFIFOQueue"                                            : QUEUE, #
    "OrderedMapUnstageNoKey"                                      : DATASTRUCTURE, #
    "TensorForestTreeResourceHandleOp"                            : NN_BOOSTED, #
    "SparseSegmentSum"                                            : MATH, #
    "FIFOQueue"                                                   : QUEUE, #
    "TensorArrayWriteV3"                                          : DATASTRUCTURE, #
    "RefMerge"                                                    : ARRAY, #
    "BitwiseOr"                                                   : BITWISE, #
    "TensorArrayScatter"                                          : DATASTRUCTURE, #
    "RestoreV2"                                                   : IO, #
    "RandomShuffleQueue"                                          : QUEUE, #
    "Invert"                                                      : BITWISE, #
    "DecodePng"                                                   : IMAGE, #
    "ControlTrigger"                                              : CONTROL, #
    "ParallelDynamicStitch"                                       : DATASTRUCTURE, #
    "MapSize"                                                     : DATASTRUCTURE, #
    "SparseReduceSum"                                             : MATH, #
    "Zeta"                                                        : MATH, #
    "TensorArrayGradV2"                                           : DATASTRUCTURE, #
    "MaxPoolGradGradWithArgmax"                                   : NN, #
    "Less"                                                        : MATH, #
    "ApplyGradientDescent"                                        : NN_OPTIM, #
    "CollectiveReduce"                                            : ARRAY, #
    "CreateSummaryFileWriter"                                     : IO_EVENT, #
    "QueueIsClosedV2"                                             : QUEUE, #
    "_ParallelConcatUpdate"                                       : INTERNAL, #If you use this function you will almost certainly want to add a control dependency as done in the implementation of parallel_stack to avoid race conditions.
    "CudnnRNNCanonicalToParams"                                   : NN, #
    "TensorArraySizeV3"                                           : DATASTRUCTURE, #
    "DiagPart"                                                    : MATH, #
    "CudnnRNNParamsToCanonical"                                   : NN, #
    "_ParallelConcatStart"                                        : INTERNAL, #The memory can optionally be initialized. This is usually useful in conjunction with inplace operations.
    "Size"                                                        : GEN, #
    "FakeQuantWithMinMaxVarsGradient"                             : ARRAY, #
    "NonMaxSuppressionV4"                                         : ARRAY, #
    "CudnnRNNBackprop"                                            : NN, #
    "Pad"                                                         : GEN, #
    "CudnnRNNV2"                                                  : NN, #
    "DynamicStitch"                                               : GEN, #
    "_Retval"                                                     : INTERNAL, #
    "CTCBeamSearchDecoder"                                        : NN, #
    "OrderedMapPeek"                                              : DATASTRUCTURE, #
    "FusedResizeAndPadConv2D"                                     : NN, #
    "Xdivy"                                                       : MATH, #
    "RefNextIteration"                                            : DATA_ITER, #
    "LogMatrixDeterminant"                                        : MATH, #
    "ExperimentalNonSerializableDataset"                          : DATA, #
    "Exit"                                                        : CONTROL, #
    "StringStrip"                                                 : STRING, #
    "RefSelect"                                                   : CONTROL, #
    "Softmax"                                                     : NN_ACTIV, #
    "ScalarSummary"                                               : IO_EVENT, #
    "Identity"                                                    : GEN, #
    "ReverseV2"                                                   : ARRAY, #
    "RefSwitch"                                                   : CONTROL, #
    "NoOp"                                                        : ARRAY, #
    "LoadAndRemapMatrix"                                          : ARRAY, #
    "IteratorFromStringHandleV2"                                  : DATA_ITER, #
    "GenerateVocabRemapping"                                      : NN, #
    "If"                                                          : CONTROL, #
    "TensorForestTreeDeserialize"                                 : NN_BOOSTED, #
    "ResourceScatterNdAdd"                                        : MATH, #
    "BoostedTreesGetEnsembleStates"                               : NN_BOOSTED, #
    "TensorForestTreeSerialize"                                   : NN_BOOSTED, #
    "MultiDeviceIterator"                                         : DATA_ITER, #
    "CudnnRNNParamsSize"                                          : NN, #
    "ExperimentalDenseToSparseBatchDataset"                       : DATA, #
    "InplaceAdd"                                                  : MATH, #
    "EnsureShape"                                                 : GEN, #
    "TensorForestTreeIsInitializedOp"                             : NN_BOOSTED, #
    "BatchSvd"                                                    : MATH, #
    "GatherV2"                                                    : ARRAY, #
    "ExperimentalParseExampleDataset"                             : INTERNAL, #
    "BoostedTreesBucketize"                                       : NN_BOOSTED, #
    "ScatterNdNonAliasingAdd"                                     : MATH, #
    "BoostedTreesQuantileStreamResourceGetBucketBoundaries"       : NN_BOOSTED, #
    "PopulationCount"                                             : ARRAY, #
    "WholeFileReaderV2"                                           : IO, #
    "BoostedTreesQuantileStreamResourceFlush"                     : NN_BOOSTED, #
    "Atan"                                                        : MATH, #
    "FakeQueue"                                                   : QUEUE, #
    "BoostedTreesPredict"                                         : NN_BOOSTED, #
    "BoostedTreesMakeStatsSummary"                                : IO_EVENT, #
    "BiasAddV1"                                                   : NN, #
    "LogicalOr"                                                   : MATH, #
    "BoostedTreesDeserializeEnsemble"                             : NN_BOOSTED, #
    "NegTrain"                                                    : NN, #
    "ConcatV2"                                                    : GEN, #
    "ConcatOffset"                                                : GEN, #
    "BoostedTreesExampleDebugOutputs"                             : INTERNAL, #
    "DecodeGif"                                                   : IMAGE, #
    "BoostedTreesCalculateBestGainsPerFeature"                    : NN_BOOSTED, #
    "SampleDistortedBoundingBox"                                  : IMAGE, #
    "DecodeBmp"                                                   : IMAGE, #
    "RightShift"                                                  : BITWISE, #
    "Imag"                                                        : MATH, #
    "MutableDenseHashTable"                                       : DATASTRUCTURE, #
    "TensorArrayGrad"                                             : DATASTRUCTURE, #
    "_MklSquaredDifference"                                       : INTERNAL, #*NOTE*: `SquaredDifference` supports broadcasting. More about broadcasting [here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
    "UnbatchGrad"                                                 : ARRAY, #
    "Mfcc"                                                        : MATH, #
    "BroadcastGradientArgs"                                       : GEN, #
    "NonMaxSuppressionV3"                                         : ARRAY, #
    "_If"                                                         : INTERNAL, #
    "BatchIFFT"                                                   : MATH, #
    "QueueDequeueUpToV2"                                          : QUEUE, #
    "DecodeWav"                                                   : AUDIO, #
    "SparseAccumulatorApplyGradient"                              : NN_OPTIM, #
    "AssignSubVariableOp"                                         : ARRAY, #
    "FusedBatchNormGrad"                                          : ARRAY, #
    "UnravelIndex"                                                : GEN, #
    "MatrixBandPart"                                              : MATH, #
    "TensorArrayClose"                                            : DATASTRUCTURE, #
    "BatchMatrixBandPart"                                         : MATH, #
    "ResizeNearestNeighbor"                                       : IMAGE, #
    "BatchMatrixDiagPart"                                         : MATH, #
    "BatchMatrixSetDiag"                                          : MATH, #
    "OnesLike"                                                    : GEN, #
    "EncodeWav"                                                   : AUDIO, #
    "FixedLengthRecordDatasetV2"                                  : DATA, #
    "IteratorGetNext"                                             : DATA_ITER, #
    "FakeQuantWithMinMaxArgsGradient"                             : ARRAY, #
    "ResourceApplyAdadelta"                                       : NN_OPTIM, #
    "BoostedTreesQuantileStreamResourceDeserialize"               : NN_BOOSTED, #
    "GetSessionHandle"                                            : ARRAY, #
    "TensorListConcat"                                            : ARRAY, #
    "FixedLengthRecordReader"                                     : IO, #
    "AssignAdd"                                                   : MATH, #
    "IsBoostedTreesQuantileStreamResourceInitialized"             : NN_BOOSTED, #
    "LeftShift"                                                   : BITWISE, #
    "EncodePng"                                                   : IMAGE, #
    "Enter"                                                       : CONTROL, #
    "StageSize"                                                   : ARRAY, #
    "RaggedTensorToSparse"                                        : RAGGED, #
    "Unique"                                                      : GEN, #
    "ScatterNd"                                                   : GEN, #
    "TensorArrayConcatV3"                                         : DATASTRUCTURE, #
    "ResourceApplyFtrlV2"                                         : NN_OPTIM, #
    "UpperBound"                                                  : MATH, #
    "StridedSliceAssign"                                          : ARRAY, #
    "QuantizedConcat"                                             : ARRAY, #
    "LookupTableInsert"                                           : LOOKUP, #
    "ExtractVolumePatches"                                        : GEN, #
    "FixedUnigramCandidateSampler"                                : PROB, #
    "Merge"                                                       : CONTROL, #
    "PaddedBatchDatasetV2"                                        : DATA, #
    "ExtractImagePatches"                                         : IMAGE, #
    "AllCandidateSampler"                                         : PROB, #
    "DepthToSpace"                                                : ARRAY, #
    "SpaceToDepth"                                                : ARRAY, #
    "InplaceSub"                                                  : MATH, #
    "RefIdentity"                                                 : MATH, #
    "FilterDataset"                                               : DATA, #
    "DeserializeSparse"                                           : IO, #
    "MapClear"                                                    : DATASTRUCTURE, #
    "QuantizedRelu6"                                              : NN, #
    "ResourceStridedSliceAssign"                                  : ARRAY, #
    "Squeeze"                                                     : GEN, #
    "InplaceUpdate"                                               : ARRAY, #
    "InitializeTableV2"                                           : DATASTRUCTURE, #
    "NextIteration"                                               : DATA_ITER, #
    "Copy"                                                        : ARRAY, #Performs CPU-to-CPU or GPU-to-GPU deep-copying of tensor, depending on the device on which the tensor is allocated. N.B.: If the all downstream attached debug ops are disabled given the current gRPC gating status, the output will simply forward the input tensor without deep-copying. See the documentation of Debug* ops for more details.  Unlike the CopyHost Op, this op does not have HostMemory constraint on its input or output.
    "StringLength"                                                : STRING, #
    "ScatterDiv"                                                  : MATH, #
    "TensorSummary"                                               : IO_EVENT, #
    "SparseApplyProximalGradientDescent"                          : NN_OPTIM, #
    "Tile"                                                        : GEN, #
    "_HostSend"                                                   : INTERNAL, #_HostSend requires its input on host memory whereas _Send requires its input on device memory.
    "ExpandDims"                                                  : GEN, #
    "SpaceToBatch"                                                : GEN, #
    "MaxPoolWithArgmax"                                           : NN, #
    "RefEnter"                                                    : CONTROL, #
    "PriorityQueueV2"                                             : QUEUE, #
    "IsBoostedTreesEnsembleInitialized"                           : NN_BOOSTED, #
    "RepeatDataset"                                               : DATA, #
    "BoostedTreesCreateEnsemble"                                  : NN_BOOSTED, #
    "Fill"                                                        : GEN, #
    "ApplyCenteredRMSProp"                                        : NN_OPTIM, #
    "Const"                                                       : GEN, #
    "PlaceholderWithDefault"                                      : ARRAY, #
    "Placeholder"                                                 : GEN, #
    "QueueEnqueueManyV2"                                          : QUEUE, #
    "Shape"                                                       : GEN, #
    "Dilation2DBackpropFilter"                                    : NN, #
    "BatchIFFT3D"                                                 : MATH, #
    "AvgPool3D"                                                   : NN, #
    "DataFormatDimMap"                                            : ARRAY, #
    "StackClose"                                                  : DATASTRUCTURE, #
    "QueueSizeV2"                                                 : QUEUE, #
    "StatelessWhile"                                              : CONTROL, #
    "MatrixDiagPart"                                              : MATH, #
    "DecodeProtoV2"                                               : ARRAY, #
    "Print"                                                       : GEN, #
    "QuantizeAndDequantizeV2"                                     : ARRAY, #
    "FractionalAvgPool"                                           : NN, #
    "SparseAccumulatorTakeGradient"                               : PROB, #
    "TruncateMod"                                                 : GEN, #
    "ResourceApplyFtrl"                                           : NN_OPTIM, #
    "StridedSliceGrad"                                            : ARRAY, #
    "QuantizeAndDequantize"                                       : ARRAY, #
    "BoostedTreesUpdateEnsemble"                                  : NN_BOOSTED, #
    "Relu6Grad"                                                   : NN_ACTIV, #
    "Range"                                                       : GEN, #
    "PrefetchDataset"                                             : DATA, #
    "DeepCopy"                                                    : ARRAY, #
    "ExperimentalLatencyStatsDataset"                             : DATA, #
    "MultiDeviceIteratorGetNextFromShard"                         : DATA_ITER, #
    "BatchCholesky"                                               : MATH, #
    "TensorArrayGather"                                           : DATASTRUCTURE, #
    "Round"                                                       : MATH, #
    "ZipDataset"                                                  : DATA, #
    "QueueClose"                                                  : QUEUE, #
    "SparseTensorDenseAdd"                                        : MATH, #
    "Snapshot"                                                    : ARRAY, #
    "UniqueV2"                                                    : ARRAY, #
    "CudnnRNNBackpropV2"                                          : NN, #
    "InvertPermutation"                                           : ARRAY, #
    "ReaderReset"                                                 : IO, #
    "StopGradient"                                                : CONTROL, #
    "ResourceScatterSub"                                          : MATH, #
    "TensorForestTreeSize"                                        : NN_BOOSTED, #
    "Rint"                                                        : MATH, #
    "Abort"                                                       : CONTROL, #
    "MutableHashTableOfTensorsV2"                                 : DATASTRUCTURE, #
    "TensorListConcatLists"                                       : ARRAY, #
    "OneHot"                                                      : ARRAY, #
    "Reverse"                                                     : GEN, #
    "BoostedTreesCreateQuantileStreamResource"                    : NN_BOOSTED, #
    "ParseSingleExample"                                          : INTERNAL, #
    "GuaranteeConst"                                              : GEN, #
    "QueueEnqueueV2"                                              : QUEUE, #
    "_ScopedAllocatorConcat"                                      : INTERNAL, #only be used in conjunction with a ScopedAllocator which is backing the memory of all of its input tensors so that actually it just outputs a read-only reference to that ScopedAllocator's backing tensor.  This is an experimental op for internal use only.  It is possible to use this op in unsafe ways.  'backing' is the backing tensor, i.e. the output of an upstream ScopedAllocator. 'inputs' is a list of nominal input tensors, all of which must be aliases to regions of the backing tensor.  These will be outputs of upstream nodes that allocate their outputs from the same ScopedAllocator. 'shape' is the shape of the output, which will usually be the same shape as the input backing tensor. 'reshape' is true iff the output shape is to be different from that of the input backing tensor. 'sa_name' is the Node name of the upstream ScopedAllocator. 'id' is the scope_id identifying the upstream ScopedAllocator. 'N' is the number of nominal inputs to be concatenated.
    "BoostedTreesQuantileStreamResourceHandleOp"                  : NN_BOOSTED, #
    "StatelessTruncatedNormal"                                    : PROB, #
    "MatrixDiag"                                                  : MATH, #
    "TensorScatterSub"                                            : MATH, #
    "FloorDiv"                                                    : MATH, #
    "StridedSlice"                                                : GEN, #
    "PreventGradient"                                             : CONTROL, #
    "SparseDenseCwiseMul"                                         : MATH, #
    "FusedPadConv2D"                                              : NN, #
    "LookupTableInsertV2"                                         : LOOKUP, #
    "BarrierInsertMany"                                           : ARRAY, #
    "SplitV"                                                      : ARRAY, #
    "BatchMatrixDiag"                                             : MATH, #
    "Bucketize"                                                   : ARRAY, #
    "DrawBoundingBoxes"                                           : IMAGE, #
    "ZerosLike"                                                   : GEN, #
    "ImageSummary"                                                : IO_EVENT, #
    "ShapeN"                                                      : GEN, #
    "HostConst"                                                   : ARRAY, #
    "Empty"                                                       : GEN, #
    "Split"                                                       : GEN, #
    "Conv3DBackpropInput"                                         : NN, #
    "DepthwiseConv2dNative"                                       : NN, #
    "LearnedUnigramCandidateSampler"                              : PROB, #
    "DebugNanCount"                                               : INTERNAL, #Counts number of NaNs in the input tensor, for debugging.
    "UnicodeScript"                                               : STRING, #
    "OptionalGetValue"                                            : ARRAY, #
    "TensorListGetItem"                                           : ARRAY, #
    "Diag"                                                        : MATH, #
    "OneShotIterator"                                             : DATA_ITER, #
    "ResourceApplyPowerSign"                                      : NN_OPTIM, #
    "Concat"                                                      : GEN, #
    "TextLineReader"                                              : IO, #
    "RecordInput"                                                 : IO, #
    "ApplyAddSign"                                                : NN_OPTIM, #
    "BitwiseAnd"                                                  : BITWISE, #
    "MatrixSetDiag"                                               : MATH, #
    "_FusedConv2D"                                                : INTERNAL, #expected to create these operators.
    "BatchFFT3D"                                                  : MATH, #
    "AdjustHue"                                                   : IMAGE, #
    "SpaceToBatchND"                                              : GEN, #
    "QuantizedMaxPool"                                            : NN, #
    "MirrorPadGrad"                                               : NN, #
    "CTCGreedyDecoder"                                            : NN, #
    "CopyHost"                                                    : ARRAY, #Performs CPU-to-CPU deep-copying of tensor. N.B.: If the all downstream attached debug ops are disabled given the current gRPC gating status, the output will simply forward the input tensor without deep-copying. See the documentation of Debug* ops for more details.  Unlike the Copy Op, this op has HostMemory constraint on its input or output.
    "MapUnstageNoKey"                                             : DATASTRUCTURE, #
    "TensorScatterAdd"                                            : ARRAY, #
    "ExperimentalMaterializedIndexDatasetHandle"                  : DATA, #
    "BoostedTreesEnsembleResourceHandleOp"                        : NN_BOOSTED, #
    "SegmentMean"                                                 : MATH, #
    "OptimizeDataset"                                             : DATA, #
    "DebugIdentity"                                               : INTERNAL, #Provides an identity mapping of the non-Ref type input tensor for debugging.
    "BroadcastArgs"                                               : GEN, #
    "DecodeCSV"                                                   : IMAGE, #
    "ExperimentalLMDBDataset"                                     : DATA, #
    "OptionalNone"                                                : ARRAY, #
    "ExperimentalNumaMapAndBatchDataset"                          : DATA, #
    "DynamicPartition"                                            : GEN, #
    "LinSpace"                                                    : MATH, #
    "FixedLengthRecordDataset"                                    : DATA, #
    "CTCLoss"                                                     : NN_LOSS, #
    "DebugGradientIdentity"                                       : INTERNAL, #
    "TensorArraySplit"                                            : DATASTRUCTURE, #
    "UnicodeEncode"                                               : STRING, #
    "Switch"                                                      : CONTROL, #
    "ResourceScatterMul"                                          : MATH, #
    "WholeFileReader"                                             : IO, #
    "ExperimentalSlidingWindowDataset"                            : DATA, #
    "TakeManySparseFromTensorsMap"                                : DATASTRUCTURE, #
    "BoostedTreesMakeQuantileSummaries"                           : NN_BOOSTED, #
    "FractionalMaxPoolGrad"                                       : NN
}.toTable

